### ISSUE TITLE
Method for registering resources

### ISSUE THREAD

**Issue by tabuna** [Nks/orchid-repeater-field#1]
I think installing the config is quite difficult to understand

https://github.com/Nks/orchid-repeater-field/blob/6d79a5d0185c3ff474f6671f2ac38c65b2293ee5/src/ServiceProvider.php#L89-L95

You can record this moment explicitly:
```php
class ServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(Dashboard $dashboard)
    {
        $dashboard->registerResource('stylesheets','/orchid/repeater.css');
        $dashboard->registerResource('scripts','/orchid/repeater.js');
    }
}
```

**Comment by Nks** [comment]
@tabuna it seems in registerResource method you are using merge for nested collections like 
```
                'stylesheets' => [
			'/css/backend.css',
		],
		'scripts'     => [
			'/js/backend.js',
		],
```
and in this case this causing the problems when it merging with same arrays. In this case it will just override everything with the config array:

![image](https://user-images.githubusercontent.com/349293/51673119-4279f380-1fde-11e9-9777-ada01d129441.png)

And next endpoint:
![image](https://user-images.githubusercontent.com/349293/51673144-532a6980-1fde-11e9-8bdd-0a0aa55c9bb6.png)

**Comment by Nks** [comment]
Blocked by https://github.com/orchidsoftware/platform/issues/765

**Comment by Nks** [comment]
Done
