### ISSUE TITLE
Публикация проекта

### ISSUE THREAD

**Issue by tabuna** [Nks/orchid-repeater-field#10]
Привет, просмотрев код, мне не очень понравилось, что каждый пакет должен иметь команду для публикации js,css файлов. По этому, создал регистрацию публичной директории, в которых бы происходил поиск запрашиваемых файлов и их отдача. Думаю, что вы будете заинтересованы в этом

**Comment by Nks** [comment]
Да, уже видел в пятницу. В понедельник использую. Спасибо.

**Comment by Nks** [comment]
Implemented.
