### ISSUE TITLE
Ошибка в 0.0.6 

### ISSUE THREAD

**Issue by PSalador** [Nks/orchid-repeater-field#11]
Протестировал - Круто!

Версия 0.0.6 почему-то выдает ошибку и не работает.

Проверял на 0.0.5 всё заработало нормально.

**Comment by PSalador** [comment]
И в composer.json думаю нужно добавить "orchid/widget".

**Comment by Nks** [comment]
@PSalador версия orchid platform?

**Comment by Nks** [comment]
@PSalador проверьте, работает ли сейчас?
