### ISSUE TITLE
Possible download error

### ISSUE THREAD

**Issue by tabuna** [Nks/orchid-repeater-field#2]
https://github.com/Nks/orchid-repeater-field/blob/6d79a5d0185c3ff474f6671f2ac38c65b2293ee5/composer.json#L20

Laravel has an excellent mechanism for registering providers for the application in the packages themselves.

But there is a high probability of a problem that manifests itself when one package depends on another, since the inherited package may be earlier. While this fundamental problem has not been resolved, I recommend that the base loader be recommended as well.

**Comment by Nks** [comment]
Removed
