### ISSUE TITLE
События

### ISSUE THREAD

**Issue by mavsan** [Nks/orchid-repeater-field#26]
Есть возможность добавить события - получение данных, после загрузки страницы (чтобы можно было прицепить события на элементы); добавление/удаление (так-же для обработчика событий) элемента Repeater?
И, так-как repeater может быть несколько разных (гипотетически, кому-то может понадобиться) - желательно при описании в Screen указывать Id нужного Repeater, чтобы в обработчике искать только нужные события.

**Comment by Nks** [comment]
Проблема заключается в том каким образом на данный момент передаются данные в скрины. Если вы поедет реализовать данный функционал который не будет ломать текущий - создавайте пулл реквест

**Comment by Nks** [comment]
Abandoned.
