### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by mavsan** [Nks/orchid-repeater-field#27]
Нет возможности указать какой из элементов `Radio` должен быть `checked`, т.к. внутри Layer нет доступа к данным `$this->query`.

**Comment by mavsan** [comment]
Я предлагаю в `Nakukryskin\OrchidRepeaterField\Http\Controllers\Systems\RepeaterController::build` добавить код:

```php
$queryData = new Repository(collect($query->toArray())->first(null, []));
$propQuery = new \ReflectionProperty($this->layout, 'query');

if($propQuery->isProtected() || $propQuery->isPrivate()) {
    $propQuery->setAccessible(true);
}

$propQuery->setValue($this->layout, $queryData);
```
Т.е. передавать данные Repository в слой.

**Comment by Nks** [comment]
PR are welcome
