### ISSUE TITLE
PHP > 7.2 is not supported

### ISSUE THREAD

**Issue by bistory** [Nks/orchid-repeater-field#44]
### Expected Behavior

Installing the package on a php 8 setup should work.

### Actual Behavior

Composer returns an error saying PHP version used by my system is not supported.

### Steps to Reproduce the Problem

  1. Use PHP 8.0 and do a composer require nakukryskin/orchid-repeater-field
  1. See it crash
  1. Profit !

### Specifications

  - ORCHID Platform Version: Latest
  - Laravel Version: 8
  - PHP Version: 8.0
  - Database Version: N/A

**Comment by modmatrix** [comment]
+1.
