### ISSUE TITLE
Repeater isn't working

### ISSUE THREAD

**Issue by kirsgithub** [Nks/orchid-repeater-field#46]
### Expected Behavior

When you click on the Add fields/rows button, it should be work.

### Actual Behavior

All libraries are connected correctly, js/css are loaded into the code.

The form page is displayed correctly and without errors, but nothing happens when you click on the Add fields/rows button. There are no js errors in the console either.

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/91856472/136037390-dfe296c0-125c-4c49-b1e0-7c09a3ff4cdb.png)

### Specifications

  - ORCHID Platform Version: 10.*
  - Laravel Version: 8.*
  - PHP Version: 7.3.29
  - Database Version:

### Other Notes

**Comment by estudiooka** [comment]
+1

**Comment by Nks** [comment]
PR are welcome

**Comment by Nks** [comment]
Done in v 13
