### ISSUE TITLE
Please fix it for Laravel 9

### ISSUE THREAD

**Issue by Sokil0** [Nks/orchid-repeater-field#51]
It's not working with Laravel 9

  BadMethodCallException

  Method Orchid\Platform\Dashboard::addPublicDirectory does not exist.

  at vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
    109▕      */
    110▕     public function __call($method, $parameters)
    111▕     {
    112▕         if (! static::hasMacro($method)) {
  ➜ 113▕             throw new BadMethodCallException(sprintf(
    114▕                 'Method %s::%s does not exist.', static::class, $method
    115▕             ));
    116▕         }
    117▕

**Comment by Nks** [comment]
https://github.com/Nks/orchid-repeater-field/pull/50

**Comment by Nks** [comment]
Done in v. 13
